v1API:  /api/auth

server:
  port: 8181

#keycloak:
#  realm: user-realm
#  auth-server-url: http://sso-srv:1443/auth/
#  ssl-required: none
#  resource: admin-panel
#  credentials:
#    secret: nOHDjssKScrKtLRgLlxrB2plwnM3ym3A
#  use-resource-role-mappings: true
#  bearer-only: true

keycloak:
  realm: master
  auth-server-url: http://sso-srv:1443/auth/
  ssl-required: external
  resource: admin-cli
  credentials:
    secret: 01z88W8qRNZFo8UkFtslEn6JUeKjQ0eQ
  use-resource-role-mappings: true
  bearer-only: true
  public-client: true